<?php
echo " Proframa orientado de objetos (POO, atributos y metodos)";
echo "En Java existen dos pilares fundamentales para crear programas eficientes: las estructuras repetitivas, que permiten ejecutar código varias veces, y la Programación Orientada a Objetos (POO), que organiza el código en clases y objetos con atributos y métodos.
Las estructuras repetitivas permiten repetir un conjunto de instrucciones automáticamente. El bucle while ejecuta su contenido mientras la condición sea verdadera, evaluando la condición antes de entrar, por lo que puede no ejecutarse ninguna vez. El do-while asegura al menos una ejecución porque la condición se evalúa al final del bloque. El for tradicional es ideal cuando se conoce el número exacto de repeticiones, ya que utiliza inicialización, condición y actualización del contador. El for-each sirve para recorrer arreglos o colecciones sin manejar índices manualmente. Además, dentro de los bucles se pueden usar las palabras clave break para salir del bucle y continue para saltar a la siguiente iteración. Es importante evitar los bucles infinitos, que ocurren cuando la condición nunca se vuelve falsa.
Por otro lado, la Programación Orientada a Objetos (POO) organiza el programa en clases y objetos. Una clase es una plantilla que define las características y acciones de los objetos, mientras que un objeto es una instancia real creada a partir de esa clase. Dentro de las clases encontramos atributos, que representan las características de un objeto (como nombre, edad, color), y métodos, que representan sus acciones o comportamientos (como saludar, caminar o sumar). Un método puede recibir parámetros y retornar valores, o simplemente ejecutar una acción.
La POO incluye el principio de encapsulación, que consiste en proteger los atributos usando el modificador private y dando acceso controlado mediante getters y setters, lo que evita cambios no deseados en los datos. Gracias a la POO, el código es más organizado, reutilizable, fácil de mantener y representa mejor objetos del mundo real.";
echo " Proframa orientado de objetos (POO, atributos y metodos)";
echo "En Java existen dos pilares fundamentales para crear programas eficientes: las estructuras repetitivas, que permiten ejecutar código varias veces, y la Programación Orientada a Objetos (POO), que organiza el código en clases y objetos con atributos y métodos.
Las estructuras repetitivas permiten repetir un conjunto de instrucciones automáticamente. El bucle while ejecuta su contenido mientras la condición sea verdadera, evaluando la condición antes de entrar, por lo que puede no ejecutarse ninguna vez. El do-while asegura al menos una ejecución porque la condición se evalúa al final del bloque. El for tradicional es ideal cuando se conoce el número exacto de repeticiones, ya que utiliza inicialización, condición y actualización del contador. El for-each sirve para recorrer arreglos o colecciones sin manejar índices manualmente. Además, dentro de los bucles se pueden usar las palabras clave break para salir del bucle y continue para saltar a la siguiente iteración. Es importante evitar los bucles infinitos, que ocurren cuando la condición nunca se vuelve falsa.
Por otro lado, la Programación Orientada a Objetos (POO) organiza el programa en clases y objetos. Una clase es una plantilla que define las características y acciones de los objetos, mientras que un objeto es una instancia real creada a partir de esa clase. Dentro de las clases encontramos atributos, que representan las características de un objeto (como nombre, edad, color), y métodos, que representan sus acciones o comportamientos (como saludar, caminar o sumar). Un método puede recibir parámetros y retornar valores, o simplemente ejecutar una acción.
La POO incluye el principio de encapsulación, que consiste en proteger los atributos usando el modificador private y dando acceso controlado mediante getters y setters, lo que evita cambios no deseados en los datos. Gracias a la POO, el código es más organizado, reutilizable, fácil de mantener y representa mejor objetos del mundo real.";

?>
